version: '3.3'

services:
  web:
    image: nginx:1.23.0
    container_name: web
    depends_on:
      - frontend
    links:
      - frontend
    volumes:
      - "./web/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
  frontend:
    image: node:18.9.1
    container_name: frontend
    volumes:
      - "./frontend/yui-loop:/projects/frontend/yui-loop"
    working_dir: /projects/frontend/yui-loop
    command: bash -c "npm i && npm start"
    ports:
      - 3000:3000
  backend:
    image: node:18.9.1
    container_name: backend
    volumes:
      - "./backend:/projects/backend"
    working_dir: /projects/backend
    command: bash -c "npm i && npm start"
    ports:
      - 5000:5000